RemoveFinalTransformer: parse complete class incl. stackmap frames + debug info
Formerly it was: PARSING_FLAGS = SKIP_DEBUG | SKIP_FRAMES.
This worked flawlessly for all application classes, but when activating group
filters in Maven Surefire,
it suddenly broke:

java.lang.VerifyError: Expecting a stackmap frame at branch target 23
Exception Details:
  Location:
    org/apache/maven/surefire/group/parse/GroupMatcherParser.group()
      Lorg/apache/maven/surefire/group/match/GroupMatcher; @14: ifeq
  Reason:
    Expected stackmap frame at this location.

So we parse the complete class with stackmap frames, debug info and all. This is
slower, but less error-prone. Better safe than sorry.